### ISSUE TITLE
If there are no passes for a student, the home view continues to load instead of displaying a message.

### ISSUE THREAD

**Issue by jpaav** [CHSCodeForChange/PassMaster-App#9]

**Comment by jpaav** [comment]
You have to do a hot restart for this my fix to work right now. I don't know if this is also true outside the Android AVD emulator so it is currently "Possibly Complete"

**Comment by armaangoel78** [comment]
yeah Id clear any builds of the the app and do it from scratch. Try this in terminal: 
`flutter clean`

**Comment by jpaav** [comment]
I was forgetting to use setState because hasPass is a state variable.
